#!/usr/bin/env bash
# This script prints "Best School"
for i in Best School,Best School,Best School,Best School,Best School,Best School,Best School,Best School,Best School,Best School; do printf $i; done | tr ',' "\n"
