#!/usr/bin/env bash
# This script will display numbers from 1 to 100 and:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

n=1

while [ $n -le 100 ]
do
	printf "%s\n" "$n"
	((n++))
done
