#!/usr/bin/env bash
# This script displays /etc/passwd content in the following format
# The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

PASSWD="/etc/passwd"

while IFS=: read -r username password userid groupid comment homedir cmdshell
	do
		echo "The user $username is part of $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
	done < $PASSWD

