#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

COUNTER=1

while [ $COUNTER -le 20 ]
do
	case $COUNTER in
		-eq 4)
			printf "%s\n" "$COUNTER"
			printf "%s\n" "bad luck from China"
			((n++))
			;;
		-eq 9)
			printf "%s\n" "$COUNTER"
			printf "%s\n" "bad luck from Japan"
			((n++))
			;;
		-eq 17)
			printf "%s\n" "$COUNTER"
			printf "%s\n" "bad luck from Italy"
			((n++))
			;;
		*)
			printf "%s\n" "$COUNTER"
			((n++))
			;;
	esac
done
