#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid
pgrep -f /var/run/myscript.pid > /var/run/myscript.pid

while true
do
	printf "%s\n" "To infinity and beyond"
	trap -arg SIGTERM
	printf "%s\n" "I hate the kill command"
	trap -arg SIGINT
	printf "%s\n" "Y U no love me?!"
	trap -arg SIGQUIT, SIGTERM
	rm /var/run/myscript.pid
done
