#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid
pgrep -f /var/run/myscript.pid > /var/run/archivotemp
cp /var/run/archivotemp /var/run/myscript.pid
rm /var/run/archivotemp

trap "echo I hate the kill command; rm /var/run/myscript.pid; pkill -f /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me ?!" SIGINT
trap "rm /var/run/myscript.pid; pkill -f /var/run/myscript.pid" SIGQUIT

while true
do
	printf "%s\n" "To infinity and beyond"
done
