#!/usr/bin/env bash
# This script manages the manage_my_process process
 
case $1 in
	start)
		sudo ./manage_my_process
		echo "$$" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -f /manage_my_process
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -f /manage_my_process
		rm /var/run/my_process.pid
		sudo ./manage_my_process
		echo "$$" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
