#!/usr/bin/env bash
# This script prints:
# -To infinity and beyond
# sleep 2
# -I am invincible!! when SIGTERM received

while true
do
	printf "%s\n" "To infinity and beyond"
	sleep 2
	trap -arg SIGTERM
	echo "I am invincible!!"
done
